// Code generated by protoc-gen-go.
// source: base.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	base.proto
	bridge.proto
	device.proto
	policy.proto
	user.proto
	version.proto

It has these top-level messages:
	LatLong
	Error
	Address
	BridgeState
	BridgeConfig
	BridgeSwUpdate
	Bridge
	GetBridgesRequest
	GetBridgesResponse
	WatchBridgesRequest
	WatchBridgesResponse
	DeviceConfig
	DeviceState
	Device
	GetDevicesRequest
	GetDevicesResponse
	GetDeviceRequest
	GetDeviceResponse
	WatchDevicesRequest
	WatchDevicesResponse
	SetDeviceConfigRequest
	SetDeviceConfigResponse
	SetDeviceStateRequest
	SetDeviceStateResponse
	ExecutionContext
	Condition
	Action
	Policy
	GetPoliciesRequest
	GetPoliciesResponse
	GetPolicyRequest
	GetPolicyResponse
	AddPolicyRequest
	AddPolicyResponse
	RemovePolicyRequest
	RemovePolicyResponse
	WatchPoliciesRequest
	WatchPoliciesResponse
	User
	VersionRequest
	VersionResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Error_Type int32

const (
	Error_UNKNOWN Error_Type = 0
)

var Error_Type_name = map[int32]string{
	0: "UNKNOWN",
}
var Error_Type_value = map[string]int32{
	"UNKNOWN": 0,
}

func (x Error_Type) String() string {
	return proto1.EnumName(Error_Type_name, int32(x))
}
func (Error_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type LatLong struct {
	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *LatLong) Reset()                    { *m = LatLong{} }
func (m *LatLong) String() string            { return proto1.CompactTextString(m) }
func (*LatLong) ProtoMessage()               {}
func (*LatLong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Error struct {
	Type    Error_Type `protobuf:"varint,1,opt,name=type,enum=proto.Error_Type" json:"type,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Details string     `protobuf:"bytes,3,opt,name=details" json:"details,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto1.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*LatLong)(nil), "proto.LatLong")
	proto1.RegisterType((*Error)(nil), "proto.Error")
	proto1.RegisterEnum("proto.Error_Type", Error_Type_name, Error_Type_value)
}

func init() { proto1.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xce, 0x5c, 0xec, 0x3e, 0x89,
	0x25, 0x3e, 0xf9, 0x79, 0xe9, 0x42, 0x52, 0x5c, 0x1c, 0x39, 0x89, 0x25, 0x99, 0x25, 0xa5, 0x29,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x4c, 0x41, 0x70, 0xbe, 0x90, 0x0c, 0x17, 0x67, 0x0e, 0x50,
	0x0d, 0x44, 0x92, 0x09, 0x2c, 0x89, 0x10, 0x50, 0x2a, 0xe7, 0x62, 0x75, 0x2d, 0x2a, 0xca, 0x2f,
	0x12, 0x52, 0xe5, 0x62, 0x29, 0xa9, 0x2c, 0x80, 0x68, 0xe7, 0x33, 0x12, 0x84, 0x58, 0xa5, 0x07,
	0x96, 0xd3, 0x0b, 0x01, 0x4a, 0x04, 0x81, 0xa5, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b,
	0x13, 0xd3, 0x21, 0x66, 0x71, 0x06, 0xc1, 0xb8, 0x20, 0x99, 0x94, 0xd4, 0x92, 0xc4, 0xcc, 0x9c,
	0x62, 0x09, 0x66, 0x88, 0x0c, 0x94, 0xab, 0x24, 0xcc, 0xc5, 0x02, 0x32, 0x41, 0x88, 0x9b, 0x8b,
	0x3d, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0xdc, 0x4f, 0x80, 0x21, 0x89, 0x0d, 0x6c, 0x81, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x44, 0x40, 0x62, 0x76, 0xd9, 0x00, 0x00, 0x00,
}
