// Code generated by protoc-gen-go.
// source: device.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WatchDevicesResponse_Action int32

const (
	WatchDevicesResponse_ADDED   WatchDevicesResponse_Action = 0
	WatchDevicesResponse_CHANGED WatchDevicesResponse_Action = 1
	WatchDevicesResponse_REMOVED WatchDevicesResponse_Action = 2
)

var WatchDevicesResponse_Action_name = map[int32]string{
	0: "ADDED",
	1: "CHANGED",
	2: "REMOVED",
}
var WatchDevicesResponse_Action_value = map[string]int32{
	"ADDED":   0,
	"CHANGED": 1,
	"REMOVED": 2,
}

func (x WatchDevicesResponse_Action) String() string {
	return proto1.EnumName(WatchDevicesResponse_Action_name, int32(x))
}
func (WatchDevicesResponse_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{8, 0}
}

type DeviceConfig struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *DeviceConfig) Reset()                    { *m = DeviceConfig{} }
func (m *DeviceConfig) String() string            { return proto1.CompactTextString(m) }
func (*DeviceConfig) ProtoMessage()               {}
func (*DeviceConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type DeviceState struct {
	IsReachable bool                          `protobuf:"varint,1,opt,name=is_reachable,json=isReachable" json:"is_reachable,omitempty"`
	Binary      *DeviceState_BinaryState      `protobuf:"bytes,11,opt,name=binary" json:"binary,omitempty"`
	Range       *DeviceState_RangeState       `protobuf:"bytes,12,opt,name=range" json:"range,omitempty"`
	ColorRgb    *DeviceState_RGBState         `protobuf:"bytes,13,opt,name=color_rgb,json=colorRgb" json:"color_rgb,omitempty"`
	Speed       *DeviceState_SpeedState       `protobuf:"bytes,14,opt,name=speed" json:"speed,omitempty"`
	Input       *DeviceState_InputState       `protobuf:"bytes,15,opt,name=input" json:"input,omitempty"`
	Control     *DeviceState_ControlState     `protobuf:"bytes,16,opt,name=control" json:"control,omitempty"`
	Temperature *DeviceState_TemperatureState `protobuf:"bytes,17,opt,name=temperature" json:"temperature,omitempty"`
	Button      []*DeviceState_ButtonState    `protobuf:"bytes,18,rep,name=button" json:"button,omitempty"`
	Presence    *DeviceState_PresenceState    `protobuf:"bytes,19,opt,name=presence" json:"presence,omitempty"`
	Version     string                        `protobuf:"bytes,100,opt,name=version" json:"version,omitempty"`
}

func (m *DeviceState) Reset()                    { *m = DeviceState{} }
func (m *DeviceState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState) ProtoMessage()               {}
func (*DeviceState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *DeviceState) GetBinary() *DeviceState_BinaryState {
	if m != nil {
		return m.Binary
	}
	return nil
}

func (m *DeviceState) GetRange() *DeviceState_RangeState {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *DeviceState) GetColorRgb() *DeviceState_RGBState {
	if m != nil {
		return m.ColorRgb
	}
	return nil
}

func (m *DeviceState) GetSpeed() *DeviceState_SpeedState {
	if m != nil {
		return m.Speed
	}
	return nil
}

func (m *DeviceState) GetInput() *DeviceState_InputState {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *DeviceState) GetControl() *DeviceState_ControlState {
	if m != nil {
		return m.Control
	}
	return nil
}

func (m *DeviceState) GetTemperature() *DeviceState_TemperatureState {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *DeviceState) GetButton() []*DeviceState_ButtonState {
	if m != nil {
		return m.Button
	}
	return nil
}

func (m *DeviceState) GetPresence() *DeviceState_PresenceState {
	if m != nil {
		return m.Presence
	}
	return nil
}

type DeviceState_BinaryState struct {
	IsOn bool `protobuf:"varint,1,opt,name=is_on,json=isOn" json:"is_on,omitempty"`
}

func (m *DeviceState_BinaryState) Reset()                    { *m = DeviceState_BinaryState{} }
func (m *DeviceState_BinaryState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_BinaryState) ProtoMessage()               {}
func (*DeviceState_BinaryState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

type DeviceState_RangeState struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *DeviceState_RangeState) Reset()                    { *m = DeviceState_RangeState{} }
func (m *DeviceState_RangeState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_RangeState) ProtoMessage()               {}
func (*DeviceState_RangeState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 1} }

type DeviceState_RGBState struct {
	Red   int32 `protobuf:"varint,1,opt,name=red" json:"red,omitempty"`
	Green int32 `protobuf:"varint,2,opt,name=green" json:"green,omitempty"`
	Blue  int32 `protobuf:"varint,3,opt,name=blue" json:"blue,omitempty"`
}

func (m *DeviceState_RGBState) Reset()                    { *m = DeviceState_RGBState{} }
func (m *DeviceState_RGBState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_RGBState) ProtoMessage()               {}
func (*DeviceState_RGBState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 2} }

type DeviceState_SpeedState struct {
	Speed int32 `protobuf:"varint,1,opt,name=speed" json:"speed,omitempty"`
}

func (m *DeviceState_SpeedState) Reset()                    { *m = DeviceState_SpeedState{} }
func (m *DeviceState_SpeedState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_SpeedState) ProtoMessage()               {}
func (*DeviceState_SpeedState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 3} }

type DeviceState_InputState struct {
	Input string `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *DeviceState_InputState) Reset()                    { *m = DeviceState_InputState{} }
func (m *DeviceState_InputState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_InputState) ProtoMessage()               {}
func (*DeviceState_InputState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 4} }

type DeviceState_ControlState struct {
	IsOpen bool `protobuf:"varint,1,opt,name=is_open,json=isOpen" json:"is_open,omitempty"`
}

func (m *DeviceState_ControlState) Reset()                    { *m = DeviceState_ControlState{} }
func (m *DeviceState_ControlState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_ControlState) ProtoMessage()               {}
func (*DeviceState_ControlState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 5} }

type DeviceState_TemperatureState struct {
	TemperatureCelsius int32 `protobuf:"varint,1,opt,name=temperature_celsius,json=temperatureCelsius" json:"temperature_celsius,omitempty"`
}

func (m *DeviceState_TemperatureState) Reset()                    { *m = DeviceState_TemperatureState{} }
func (m *DeviceState_TemperatureState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_TemperatureState) ProtoMessage()               {}
func (*DeviceState_TemperatureState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 6} }

type DeviceState_ButtonState struct {
	Id   int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	IsOn bool  `protobuf:"varint,2,opt,name=is_on,json=isOn" json:"is_on,omitempty"`
}

func (m *DeviceState_ButtonState) Reset()                    { *m = DeviceState_ButtonState{} }
func (m *DeviceState_ButtonState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_ButtonState) ProtoMessage()               {}
func (*DeviceState_ButtonState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 7} }

type DeviceState_PresenceState struct {
	IsPresent bool `protobuf:"varint,1,opt,name=is_present,json=isPresent" json:"is_present,omitempty"`
}

func (m *DeviceState_PresenceState) Reset()                    { *m = DeviceState_PresenceState{} }
func (m *DeviceState_PresenceState) String() string            { return proto1.CompactTextString(m) }
func (*DeviceState_PresenceState) ProtoMessage()               {}
func (*DeviceState_PresenceState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 8} }

type Device struct {
	Id               string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	IsActive         bool                `protobuf:"varint,2,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	ModelId          string              `protobuf:"bytes,10,opt,name=model_id,json=modelId" json:"model_id,omitempty"`
	ModelName        string              `protobuf:"bytes,11,opt,name=model_name,json=modelName" json:"model_name,omitempty"`
	ModelDescription string              `protobuf:"bytes,12,opt,name=model_description,json=modelDescription" json:"model_description,omitempty"`
	Manufacturer     string              `protobuf:"bytes,13,opt,name=manufacturer" json:"manufacturer,omitempty"`
	Address          string              `protobuf:"bytes,50,opt,name=address" json:"address,omitempty"`
	Range            *Device_RangeDevice `protobuf:"bytes,100,opt,name=range" json:"range,omitempty"`
	Input            *Device_InputDevice `protobuf:"bytes,101,opt,name=input" json:"input,omitempty"`
	Speed            *Device_SpeedDevice `protobuf:"bytes,102,opt,name=speed" json:"speed,omitempty"`
	Config           *DeviceConfig       `protobuf:"bytes,200,opt,name=config" json:"config,omitempty"`
	State            *DeviceState        `protobuf:"bytes,201,opt,name=state" json:"state,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto1.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Device) GetRange() *Device_RangeDevice {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Device) GetInput() *Device_InputDevice {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Device) GetSpeed() *Device_SpeedDevice {
	if m != nil {
		return m.Speed
	}
	return nil
}

func (m *Device) GetConfig() *DeviceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Device) GetState() *DeviceState {
	if m != nil {
		return m.State
	}
	return nil
}

// Examples could include a thermostat.
type Device_RangeDevice struct {
	Minimum int32 `protobuf:"varint,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum int32 `protobuf:"varint,2,opt,name=maximum" json:"maximum,omitempty"`
}

func (m *Device_RangeDevice) Reset()                    { *m = Device_RangeDevice{} }
func (m *Device_RangeDevice) String() string            { return proto1.CompactTextString(m) }
func (*Device_RangeDevice) ProtoMessage()               {}
func (*Device_RangeDevice) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2, 0} }

// Examples could include a TV (list of inputs), speakers (list of inputs), etc.
type Device_InputDevice struct {
	Inputs []string `protobuf:"bytes,1,rep,name=inputs" json:"inputs,omitempty"`
}

func (m *Device_InputDevice) Reset()                    { *m = Device_InputDevice{} }
func (m *Device_InputDevice) String() string            { return proto1.CompactTextString(m) }
func (*Device_InputDevice) ProtoMessage()               {}
func (*Device_InputDevice) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2, 1} }

// Examples could include a fan,
type Device_SpeedDevice struct {
	Maximum int32 `protobuf:"varint,1,opt,name=maximum" json:"maximum,omitempty"`
}

func (m *Device_SpeedDevice) Reset()                    { *m = Device_SpeedDevice{} }
func (m *Device_SpeedDevice) String() string            { return proto1.CompactTextString(m) }
func (*Device_SpeedDevice) ProtoMessage()               {}
func (*Device_SpeedDevice) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2, 2} }

type GetDevicesRequest struct {
}

func (m *GetDevicesRequest) Reset()                    { *m = GetDevicesRequest{} }
func (m *GetDevicesRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetDevicesRequest) ProtoMessage()               {}
func (*GetDevicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type GetDevicesResponse struct {
	Devices []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
}

func (m *GetDevicesResponse) Reset()                    { *m = GetDevicesResponse{} }
func (m *GetDevicesResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetDevicesResponse) ProtoMessage()               {}
func (*GetDevicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GetDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *GetDeviceRequest) Reset()                    { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()               {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type GetDeviceResponse struct {
	Device *Device `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
}

func (m *GetDeviceResponse) Reset()                    { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()               {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GetDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type WatchDevicesRequest struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *WatchDevicesRequest) Reset()                    { *m = WatchDevicesRequest{} }
func (m *WatchDevicesRequest) String() string            { return proto1.CompactTextString(m) }
func (*WatchDevicesRequest) ProtoMessage()               {}
func (*WatchDevicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

type WatchDevicesResponse struct {
	Action WatchDevicesResponse_Action `protobuf:"varint,1,opt,name=action,enum=proto.WatchDevicesResponse_Action" json:"action,omitempty"`
	Device *Device                     `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
}

func (m *WatchDevicesResponse) Reset()                    { *m = WatchDevicesResponse{} }
func (m *WatchDevicesResponse) String() string            { return proto1.CompactTextString(m) }
func (*WatchDevicesResponse) ProtoMessage()               {}
func (*WatchDevicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *WatchDevicesResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type SetDeviceConfigRequest struct {
	Address string        `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Version string        `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Config  *DeviceConfig `protobuf:"bytes,10,opt,name=config" json:"config,omitempty"`
}

func (m *SetDeviceConfigRequest) Reset()                    { *m = SetDeviceConfigRequest{} }
func (m *SetDeviceConfigRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetDeviceConfigRequest) ProtoMessage()               {}
func (*SetDeviceConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *SetDeviceConfigRequest) GetConfig() *DeviceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetDeviceConfigResponse struct {
	Error  string  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Device *Device `protobuf:"bytes,10,opt,name=device" json:"device,omitempty"`
}

func (m *SetDeviceConfigResponse) Reset()                    { *m = SetDeviceConfigResponse{} }
func (m *SetDeviceConfigResponse) String() string            { return proto1.CompactTextString(m) }
func (*SetDeviceConfigResponse) ProtoMessage()               {}
func (*SetDeviceConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *SetDeviceConfigResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type SetDeviceStateRequest struct {
	Address string       `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Version string       `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	State   *DeviceState `protobuf:"bytes,10,opt,name=state" json:"state,omitempty"`
}

func (m *SetDeviceStateRequest) Reset()                    { *m = SetDeviceStateRequest{} }
func (m *SetDeviceStateRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetDeviceStateRequest) ProtoMessage()               {}
func (*SetDeviceStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *SetDeviceStateRequest) GetState() *DeviceState {
	if m != nil {
		return m.State
	}
	return nil
}

type SetDeviceStateResponse struct {
	Error  string  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Device *Device `protobuf:"bytes,10,opt,name=device" json:"device,omitempty"`
}

func (m *SetDeviceStateResponse) Reset()                    { *m = SetDeviceStateResponse{} }
func (m *SetDeviceStateResponse) String() string            { return proto1.CompactTextString(m) }
func (*SetDeviceStateResponse) ProtoMessage()               {}
func (*SetDeviceStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *SetDeviceStateResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func init() {
	proto1.RegisterType((*DeviceConfig)(nil), "proto.DeviceConfig")
	proto1.RegisterType((*DeviceState)(nil), "proto.DeviceState")
	proto1.RegisterType((*DeviceState_BinaryState)(nil), "proto.DeviceState.BinaryState")
	proto1.RegisterType((*DeviceState_RangeState)(nil), "proto.DeviceState.RangeState")
	proto1.RegisterType((*DeviceState_RGBState)(nil), "proto.DeviceState.RGBState")
	proto1.RegisterType((*DeviceState_SpeedState)(nil), "proto.DeviceState.SpeedState")
	proto1.RegisterType((*DeviceState_InputState)(nil), "proto.DeviceState.InputState")
	proto1.RegisterType((*DeviceState_ControlState)(nil), "proto.DeviceState.ControlState")
	proto1.RegisterType((*DeviceState_TemperatureState)(nil), "proto.DeviceState.TemperatureState")
	proto1.RegisterType((*DeviceState_ButtonState)(nil), "proto.DeviceState.ButtonState")
	proto1.RegisterType((*DeviceState_PresenceState)(nil), "proto.DeviceState.PresenceState")
	proto1.RegisterType((*Device)(nil), "proto.Device")
	proto1.RegisterType((*Device_RangeDevice)(nil), "proto.Device.RangeDevice")
	proto1.RegisterType((*Device_InputDevice)(nil), "proto.Device.InputDevice")
	proto1.RegisterType((*Device_SpeedDevice)(nil), "proto.Device.SpeedDevice")
	proto1.RegisterType((*GetDevicesRequest)(nil), "proto.GetDevicesRequest")
	proto1.RegisterType((*GetDevicesResponse)(nil), "proto.GetDevicesResponse")
	proto1.RegisterType((*GetDeviceRequest)(nil), "proto.GetDeviceRequest")
	proto1.RegisterType((*GetDeviceResponse)(nil), "proto.GetDeviceResponse")
	proto1.RegisterType((*WatchDevicesRequest)(nil), "proto.WatchDevicesRequest")
	proto1.RegisterType((*WatchDevicesResponse)(nil), "proto.WatchDevicesResponse")
	proto1.RegisterType((*SetDeviceConfigRequest)(nil), "proto.SetDeviceConfigRequest")
	proto1.RegisterType((*SetDeviceConfigResponse)(nil), "proto.SetDeviceConfigResponse")
	proto1.RegisterType((*SetDeviceStateRequest)(nil), "proto.SetDeviceStateRequest")
	proto1.RegisterType((*SetDeviceStateResponse)(nil), "proto.SetDeviceStateResponse")
	proto1.RegisterEnum("proto.WatchDevicesResponse_Action", WatchDevicesResponse_Action_name, WatchDevicesResponse_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for DeviceManager service

type DeviceManagerClient interface {
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	WatchDevices(ctx context.Context, in *WatchDevicesRequest, opts ...grpc.CallOption) (DeviceManager_WatchDevicesClient, error)
	SetDeviceConfig(ctx context.Context, in *SetDeviceConfigRequest, opts ...grpc.CallOption) (*SetDeviceConfigResponse, error)
	SetDeviceState(ctx context.Context, in *SetDeviceStateRequest, opts ...grpc.CallOption) (*SetDeviceStateResponse, error)
}

type deviceManagerClient struct {
	cc *grpc.ClientConn
}

func NewDeviceManagerClient(cc *grpc.ClientConn) DeviceManagerClient {
	return &deviceManagerClient{cc}
}

func (c *deviceManagerClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error) {
	out := new(GetDevicesResponse)
	err := grpc.Invoke(ctx, "/proto.DeviceManager/GetDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagerClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := grpc.Invoke(ctx, "/proto.DeviceManager/GetDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagerClient) WatchDevices(ctx context.Context, in *WatchDevicesRequest, opts ...grpc.CallOption) (DeviceManager_WatchDevicesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DeviceManager_serviceDesc.Streams[0], c.cc, "/proto.DeviceManager/WatchDevices", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceManagerWatchDevicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceManager_WatchDevicesClient interface {
	Recv() (*WatchDevicesResponse, error)
	grpc.ClientStream
}

type deviceManagerWatchDevicesClient struct {
	grpc.ClientStream
}

func (x *deviceManagerWatchDevicesClient) Recv() (*WatchDevicesResponse, error) {
	m := new(WatchDevicesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceManagerClient) SetDeviceConfig(ctx context.Context, in *SetDeviceConfigRequest, opts ...grpc.CallOption) (*SetDeviceConfigResponse, error) {
	out := new(SetDeviceConfigResponse)
	err := grpc.Invoke(ctx, "/proto.DeviceManager/SetDeviceConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagerClient) SetDeviceState(ctx context.Context, in *SetDeviceStateRequest, opts ...grpc.CallOption) (*SetDeviceStateResponse, error) {
	out := new(SetDeviceStateResponse)
	err := grpc.Invoke(ctx, "/proto.DeviceManager/SetDeviceState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeviceManager service

type DeviceManagerServer interface {
	GetDevices(context.Context, *GetDevicesRequest) (*GetDevicesResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	WatchDevices(*WatchDevicesRequest, DeviceManager_WatchDevicesServer) error
	SetDeviceConfig(context.Context, *SetDeviceConfigRequest) (*SetDeviceConfigResponse, error)
	SetDeviceState(context.Context, *SetDeviceStateRequest) (*SetDeviceStateResponse, error)
}

func RegisterDeviceManagerServer(s *grpc.Server, srv DeviceManagerServer) {
	s.RegisterService(&_DeviceManager_serviceDesc, srv)
}

func _DeviceManager_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeviceManager/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServer).GetDevices(ctx, req.(*GetDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManager_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeviceManager/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManager_WatchDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceManagerServer).WatchDevices(m, &deviceManagerWatchDevicesServer{stream})
}

type DeviceManager_WatchDevicesServer interface {
	Send(*WatchDevicesResponse) error
	grpc.ServerStream
}

type deviceManagerWatchDevicesServer struct {
	grpc.ServerStream
}

func (x *deviceManagerWatchDevicesServer) Send(m *WatchDevicesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DeviceManager_SetDeviceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServer).SetDeviceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeviceManager/SetDeviceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServer).SetDeviceConfig(ctx, req.(*SetDeviceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManager_SetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServer).SetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeviceManager/SetDeviceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServer).SetDeviceState(ctx, req.(*SetDeviceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DeviceManager",
	HandlerType: (*DeviceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _DeviceManager_GetDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _DeviceManager_GetDevice_Handler,
		},
		{
			MethodName: "SetDeviceConfig",
			Handler:    _DeviceManager_SetDeviceConfig_Handler,
		},
		{
			MethodName: "SetDeviceState",
			Handler:    _DeviceManager_SetDeviceState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDevices",
			Handler:       _DeviceManager_WatchDevices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor2,
}

func init() { proto1.RegisterFile("device.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1079 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0xaf, 0x9d, 0xf8, 0xdf, 0x9c, 0x93, 0x3a, 0xeb, 0xd2, 0x5c, 0x2e, 0x4d, 0x09, 0x87, 0xaa,
	0x16, 0x51, 0x1c, 0xe4, 0x48, 0x08, 0x2a, 0x90, 0x70, 0xed, 0x10, 0x2a, 0xd4, 0x06, 0x5d, 0xa0,
	0x7c, 0xb4, 0xce, 0xe7, 0x8d, 0x7b, 0x92, 0x7d, 0x67, 0xee, 0xce, 0x11, 0x7d, 0x03, 0x1e, 0x85,
	0x47, 0x81, 0x47, 0xe0, 0x61, 0x90, 0xd8, 0x9d, 0xd9, 0xb5, 0xf7, 0x9c, 0x73, 0xf2, 0x01, 0x3e,
	0xe5, 0x66, 0xe7, 0xf7, 0x9b, 0xd9, 0x9d, 0xf9, 0xcd, 0x38, 0xd0, 0x1c, 0xf3, 0xeb, 0x30, 0xe0,
	0x9d, 0x79, 0x12, 0x67, 0x31, 0xab, 0xe0, 0x1f, 0x77, 0x00, 0xcd, 0x01, 0x1e, 0xf7, 0xe3, 0xe8,
	0x2a, 0x9c, 0x30, 0x06, 0xdb, 0x91, 0x3f, 0xe3, 0x76, 0xe9, 0xb8, 0xf4, 0xac, 0xe1, 0xe1, 0x37,
	0x3b, 0x06, 0x6b, 0xcc, 0xd3, 0x20, 0x09, 0xe7, 0x59, 0x18, 0x47, 0x76, 0x19, 0x5d, 0xe6, 0x91,
	0xfb, 0x4f, 0x0d, 0x2c, 0x0a, 0x73, 0x99, 0xf9, 0x19, 0x67, 0x1f, 0x41, 0x33, 0x4c, 0x87, 0x09,
	0xf7, 0x83, 0x77, 0xfe, 0x68, 0x4a, 0xd1, 0xea, 0x9e, 0x15, 0xa6, 0x9e, 0x3e, 0x62, 0x5f, 0x40,
	0x75, 0x14, 0x46, 0x7e, 0xf2, 0xde, 0xb6, 0x84, 0xd3, 0xea, 0x3e, 0xa6, 0x7b, 0x75, 0x8c, 0x30,
	0x9d, 0x97, 0x08, 0xc0, 0x6f, 0x4f, 0xa1, 0xd9, 0x29, 0x54, 0x12, 0x3f, 0x9a, 0x70, 0xbb, 0x89,
	0xb4, 0xa3, 0x02, 0x9a, 0x27, 0xfd, 0xc4, 0x22, 0x2c, 0xfb, 0x12, 0x1a, 0x41, 0x3c, 0x8d, 0x93,
	0x61, 0x32, 0x19, 0xd9, 0x3b, 0x48, 0x3c, 0x2c, 0x22, 0x9e, 0xbf, 0x24, 0x5a, 0x1d, 0xd1, 0xde,
	0x64, 0x24, 0xd3, 0xa5, 0x73, 0xce, 0xc7, 0xf6, 0xee, 0xc6, 0x74, 0x97, 0xd2, 0xaf, 0xd2, 0x21,
	0x56, 0x92, 0xc2, 0x68, 0xbe, 0xc8, 0xec, 0xfb, 0x1b, 0x49, 0xaf, 0xa4, 0x5f, 0x91, 0x10, 0xcb,
	0xbe, 0x82, 0x5a, 0x10, 0x47, 0x59, 0x12, 0x4f, 0xed, 0x16, 0xd2, 0x3e, 0x2c, 0xa0, 0xf5, 0x09,
	0x41, 0x44, 0x8d, 0x67, 0x67, 0x60, 0x65, 0x7c, 0x36, 0xe7, 0x89, 0x9f, 0x2d, 0x12, 0x6e, 0xef,
	0x21, 0xfd, 0xe3, 0x02, 0xfa, 0x4f, 0x2b, 0x14, 0x85, 0x30, 0x79, 0xd8, 0x92, 0x45, 0x96, 0x89,
	0x16, 0xb3, 0xe3, 0xad, 0x4d, 0x2d, 0x41, 0x80, 0x6e, 0x09, 0x1a, 0xec, 0x6b, 0xa8, 0xcf, 0x13,
	0x9e, 0xf2, 0x28, 0xe0, 0x76, 0x1b, 0x73, 0x1f, 0x17, 0x30, 0x7f, 0x54, 0x10, 0x55, 0x61, 0xcd,
	0x60, 0x36, 0xd4, 0xae, 0x79, 0x92, 0x4a, 0x65, 0x8d, 0x51, 0x59, 0xda, 0x74, 0x5c, 0xb0, 0x0c,
	0x05, 0xb0, 0xb6, 0xa8, 0x6a, 0x3a, 0x14, 0x30, 0x52, 0xd3, 0x76, 0x98, 0x5e, 0x48, 0x0c, 0xac,
	0xda, 0xcd, 0x1e, 0x40, 0xe5, 0xda, 0x9f, 0x2e, 0x48, 0x70, 0x15, 0x8f, 0x0c, 0xe7, 0x3b, 0xa8,
	0xeb, 0xce, 0xb2, 0x16, 0x6c, 0x25, 0xa2, 0x9b, 0xe4, 0x97, 0x9f, 0x92, 0x33, 0x49, 0x38, 0x27,
	0x5d, 0x0b, 0x0e, 0x1a, 0x72, 0x0e, 0x46, 0x32, 0xd0, 0x16, 0x1e, 0xe2, 0xb7, 0xcc, 0xb5, 0xea,
	0xb5, 0xe4, 0x91, 0x32, 0x54, 0x2e, 0x34, 0x24, 0x66, 0xd5, 0x5a, 0x89, 0x21, 0x21, 0xd0, 0x38,
	0x91, 0xe1, 0x3c, 0x85, 0xa6, 0xd9, 0x47, 0xb6, 0x0f, 0x35, 0xf9, 0xb0, 0x39, 0xd7, 0x4f, 0xab,
	0x8a, 0xa7, 0x09, 0xcb, 0xe9, 0x43, 0x6b, 0xbd, 0x63, 0xec, 0x04, 0xda, 0x46, 0xcf, 0x86, 0x01,
	0x9f, 0xa6, 0xe1, 0x22, 0x55, 0x97, 0x60, 0x86, 0xab, 0x4f, 0x1e, 0xa7, 0x2b, 0xaa, 0xb8, 0x6a,
	0x1a, 0xdb, 0x85, 0x72, 0xa8, 0xef, 0x2c, 0xbe, 0x56, 0x55, 0x2d, 0x1b, 0x55, 0xed, 0xc0, 0x4e,
	0xae, 0x5d, 0xec, 0x08, 0x40, 0xa0, 0xa8, 0x67, 0x99, 0xba, 0x65, 0x23, 0x4c, 0x09, 0x94, 0xb9,
	0x7f, 0x6f, 0x43, 0x95, 0x7a, 0x6d, 0xc4, 0x6f, 0x60, 0xfc, 0x43, 0x10, 0xb8, 0xa1, 0x1f, 0x64,
	0xe1, 0x35, 0x57, 0x39, 0xea, 0x61, 0xda, 0x43, 0x9b, 0x1d, 0x40, 0x7d, 0x16, 0x8f, 0xf9, 0x74,
	0x28, 0x28, 0x40, 0xcd, 0x47, 0xfb, 0xd5, 0x58, 0x66, 0x24, 0x17, 0xae, 0x23, 0x0b, 0x9d, 0x0d,
	0x3c, 0x79, 0x23, 0x77, 0xd2, 0xa7, 0xb0, 0x47, 0x6e, 0x73, 0x33, 0x35, 0x11, 0xd5, 0x42, 0xc7,
	0x60, 0x75, 0xce, 0x5c, 0x68, 0xce, 0xfc, 0x68, 0x71, 0x25, 0x6e, 0x21, 0x0a, 0x93, 0xe0, 0x06,
	0x68, 0x78, 0xb9, 0x33, 0x29, 0x43, 0x7f, 0x3c, 0x16, 0xef, 0x49, 0xed, 0x2e, 0xdd, 0x44, 0x99,
	0xa2, 0xe2, 0x6a, 0xe3, 0x8c, 0x51, 0xdb, 0x07, 0x39, 0x6d, 0xd3, 0xb2, 0xa1, 0x6f, 0xbd, 0x6d,
	0x4e, 0x74, 0xd7, 0x79, 0x11, 0x01, 0xe5, 0xa1, 0x09, 0x34, 0xfa, 0x27, 0x5a, 0x4a, 0x57, 0x45,
	0x04, 0xd4, 0x9c, 0x26, 0xd0, 0x82, 0x79, 0x0e, 0xd5, 0x00, 0xf7, 0xb5, 0xfd, 0x67, 0x09, 0x29,
	0xed, 0x1c, 0x85, 0x76, 0xb9, 0xa7, 0x30, 0xec, 0x13, 0x11, 0x5e, 0x76, 0xd1, 0xfe, 0x8b, 0xc0,
	0xec, 0xe6, 0x74, 0x7a, 0x84, 0x70, 0x7a, 0x60, 0x19, 0x0f, 0x92, 0x45, 0x99, 0x85, 0x51, 0x38,
	0x5b, 0xcc, 0x94, 0x62, 0xb4, 0x89, 0x1e, 0xff, 0x37, 0xf4, 0x94, 0x95, 0x87, 0x4c, 0xe7, 0x09,
	0x58, 0xc6, 0x13, 0xd9, 0x43, 0xa8, 0xe2, 0x23, 0xa5, 0x44, 0xb7, 0x44, 0x59, 0x95, 0x25, 0x86,
	0xc0, 0x32, 0x1e, 0x66, 0xc6, 0x2b, 0xe5, 0xe2, 0xb9, 0x6d, 0xd8, 0x3b, 0xe7, 0x2a, 0x9a, 0xf8,
	0xfd, 0xf8, 0x75, 0xc1, 0xd3, 0xcc, 0xfd, 0x06, 0x98, 0x79, 0x98, 0xce, 0xe3, 0x28, 0xe5, 0xec,
	0x29, 0xd4, 0xe8, 0x37, 0x8e, 0x92, 0x59, 0xdd, 0x9d, 0xdc, 0x4b, 0x3d, 0xed, 0x75, 0x9f, 0x43,
	0x6b, 0x49, 0x57, 0x21, 0x4d, 0x01, 0x94, 0x72, 0x02, 0x70, 0x5f, 0x18, 0x37, 0x58, 0xe6, 0x7a,
	0x02, 0x55, 0x8a, 0x66, 0x53, 0x51, 0xd7, 0x52, 0x29, 0xa7, 0x7b, 0x0a, 0xed, 0x5f, 0xfc, 0x2c,
	0x78, 0x97, 0xbf, 0x3f, 0x7b, 0x04, 0x0d, 0x15, 0x9d, 0xeb, 0xc2, 0xac, 0x0e, 0xdc, 0x3f, 0x4a,
	0xf0, 0x20, 0xcf, 0x52, 0x49, 0x5f, 0x40, 0x55, 0x4e, 0x92, 0xda, 0x81, 0xbb, 0x5d, 0x57, 0x25,
	0x2d, 0x02, 0x77, 0x7a, 0x88, 0xf4, 0x14, 0xc3, 0xb8, 0x70, 0xf9, 0xb6, 0x0b, 0x7f, 0x06, 0x55,
	0x22, 0xb2, 0x06, 0x54, 0x7a, 0x83, 0xc1, 0xd9, 0xa0, 0x75, 0x8f, 0x59, 0x50, 0xeb, 0x7f, 0xdf,
	0x7b, 0x73, 0x2e, 0x8c, 0x92, 0x34, 0xbc, 0xb3, 0xd7, 0x17, 0x6f, 0x85, 0x51, 0x76, 0xdf, 0xc3,
	0xc3, 0x4b, 0x5d, 0x1b, 0x25, 0xbb, 0xbb, 0xea, 0x69, 0x6e, 0xfc, 0x72, 0x6e, 0xe3, 0x8b, 0xa9,
	0xd6, 0xba, 0x86, 0x3b, 0x65, 0xed, 0xbe, 0x85, 0xfd, 0x1b, 0xa9, 0x55, 0x9d, 0xc4, 0xde, 0xe5,
	0x49, 0x12, 0x27, 0x7a, 0xef, 0xa2, 0x61, 0x54, 0x00, 0x6e, 0xab, 0xc0, 0x02, 0x3e, 0x58, 0xc6,
	0xa5, 0xe1, 0xf8, 0x0f, 0x2f, 0x7a, 0xa6, 0x67, 0x0f, 0xee, 0x18, 0x3d, 0xf7, 0x67, 0xa3, 0x92,
	0x2a, 0xed, 0xff, 0xf0, 0x9a, 0xee, 0xef, 0x5b, 0xb0, 0x43, 0x47, 0xaf, 0xfd, 0xc8, 0x9f, 0x88,
	0x4d, 0xd7, 0x07, 0x58, 0xcd, 0x0e, 0xb3, 0x15, 0xed, 0xc6, 0x8c, 0x39, 0x07, 0x05, 0x1e, 0xba,
	0x91, 0x7b, 0x8f, 0x7d, 0x0b, 0x8d, 0xe5, 0x39, 0xdb, 0x5f, 0x47, 0xea, 0x10, 0xf6, 0x4d, 0xc7,
	0x32, 0xc2, 0x0f, 0xd0, 0x34, 0x65, 0xcb, 0x9c, 0x42, 0x2d, 0x53, 0x9c, 0xc3, 0x5b, 0x74, 0xee,
	0xde, 0xfb, 0xbc, 0xc4, 0x3c, 0xb8, 0xbf, 0xa6, 0x05, 0xa6, 0xff, 0xeb, 0x2a, 0x96, 0xa7, 0xf3,
	0x78, 0x93, 0x7b, 0x79, 0xc1, 0x0b, 0xd8, 0xcd, 0x37, 0x84, 0x3d, 0x5a, 0xe7, 0x98, 0xf2, 0x70,
	0x8e, 0x36, 0x78, 0x75, 0xc0, 0x51, 0x15, 0xfd, 0xa7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x91,
	0x9e, 0xcd, 0x45, 0x89, 0x0b, 0x00, 0x00,
}
